setwd("C:/Users/Data 1/Desktop/SANOFI/Validation des models/Validation erreurs/tend saiso")

ventes<-read.table("ventes_avec_pub.csv", sep = ";", header = T, fill = T, quote = "", encoding = 'UTF-8')
ventes<-ventes[ventes$anneemois<201601,]
library("TTR")
library("stringi")

detrend <- function(ventes,marque='TOPLEXIL_BU') {
toplexil<-ventes[ventes$segment_produit==marque,]

#var<-c(ventes$segment_produit,ventes$anneemois,ventes$CAnet)
#toplexil<-toplexil[,c(8,9,10)]

toplexil$date <- stri_sub(as.character(toplexil$anneemois), 5,6)

toplexil<-unique(toplexil)

toplexil<-toplexil[order(toplexil[,2]),]

toplex <- ts(toplexil[,3], frequency=12, start=c(2012,1))
toplex

plot.ts(toplex)


toplex_components <- decompose(toplex)

plot(toplex_components)
return(toplex_components)

}
 table(ventes$segment_produit)

 aspegique<-detrend(ventes,marque='ASPEGIC/MIGPRIV')
 ATURGYL<-detrend(ventes,marque='ATURGYL')
 AVIBON<-detrend(ventes,marque='AVIBON')
 BALSOFUMINE<-detrend(ventes,marque='BALSOFUMINE')
 BRONCHOKOD_RHINATHIOL_BRONCHOKOD<-detrend(ventes,marque='BRONCHOKOD & RHINATHIOL / BRONCHOKOD')
 BRONCHOKOD_RHINATHIOL_RHINATHIOL<-detrend(ventes,marque='BRONCHOKOD & RHINATHIOL / RHINATHIOL')
 CODOLIPRANE_BU<-detrend(ventes,marque='CODOLIPRANE_BU')
 DECONTRACT<-detrend(ventes,marque='DECONTRACT')
 DERMACHROM<-detrend(ventes,marque='DERMACHROM')
 DIAMOX<-detrend(ventes,marque='DIAMOX')
 DOLI_ETAT_GRIPPAL<-detrend(ventes,marque='DOLI_ETAT_GRIPPAL')
 DOLI_MAUX_DE_GORGE<-detrend(ventes,marque='DOLI_MAUX_DE_GORGE')
 DOLIALLERGIE<-detrend(ventes,marque='DOLIALLERGIE')
 DOLIPRANE_GENERALIST<-detrend(ventes,marque='DOLIPRANE GENERALIST')
 DOLIRHUME<-detrend(ventes,marque='DOLIRHUME')
 ENDOTELON_BU<-detrend(ventes,marque='ENDOTELON_BU')
 ERCEFURYL<-detrend(ventes,marque='ERCEFURYL')
 ETIOVEN<-detrend(ventes,marque='ETIOVEN')
 HEMOCLAR<-detrend(ventes,marque='HEMOCLAR')
 HEPTAMYL<-detrend(ventes,marque='HEPTAMYL')
 HEXOMEDINE_BU<-detrend(ventes,marque='HEXOMEDINE_BU')
 IPRAALOX<-detrend(ventes,marque='IPRAALOX')
 MAALOX<-detrend(ventes,marque='MAALOX')
 MAGNE_B6_MAGNE_VIE<-detrend(ventes,marque='MAGNE B6 & MAGNE VIE')
 MAXILASE_BU<-detrend(ventes,marque='MAXILASE_BU')
 MITOCORTYL<-detrend(ventes,marque='MITOCORTYL')
 MITOSYL<-detrend(ventes,marque='MITOSYL')
 NAUTAMINE<-detrend(ventes,marque='NAUTAMINE')
 NOVA_HEALTH_DIVERS_NOVA_SANTE<-detrend(ventes,marque='NOVA HEALTH / DIVERS NOVA SANTE')
 NOVA_HEALTH_NOVABIOSTIM<-detrend(ventes,marque='NOVA HEALTH / NOVABIOSTIM')
 NOVA_HEALTH_NOVALGIC<-detrend(ventes,marque='NOVA HEALTH / NOVALGIC')
 NOVA_HEALTH_NOVANIGHT<-detrend(ventes,marque='NOVA HEALTH / NOVANIGHT')
 NOVA_HEALTH_NOVASTEROL<-detrend(ventes,marque='NOVA HEALTH / NOVASTEROL')
 NOVA_HEALTH_NOVASTIM<-detrend(ventes,marque='NOVA HEALTH / NOVASTIM')
 NOVA_HEALTH_NOVAZEN<-detrend(ventes,marque='NOVA HEALTH / NOVAZEN')
 NOVALAC_BU<-detrend(ventes,marque='NOVALAC_BU')
 OENOBIOL_BU_ACTIV_OPC<-detrend(ventes,marque='OENOBIOL_BU / ACTIV OPC')
 OENOBIOL_BU_ANTI_AGE<-detrend(ventes,marque='OENOBIOL_BU / ANTI-AGE')
 OENOBIOL_BU_ANTI_CHUTE<-detrend(ventes,marque='OENOBIOL_BU / ANTI-CHUTE')
 OENOBIOL_BU_ANTI_RIDES<-detrend(ventes,marque='OENOBIOL_BU / ANTI-RIDES')
 OENOBIOL_BU_AQUADRAINANT<-detrend(ventes,marque='OENOBIOL_BU / AQUADRAINANT')
 OENOBIOL_BU_AUTOBRONZANT<-detrend(ventes,marque='OENOBIOL_BU / AUTOBRONZANT')
 OENOBIOL_BU_BEAUTE_DES_CHEVEUX<-detrend(ventes,marque='OENOBIOL_BU / BEAUTE DES CHEVEUX')
 OENOBIOL_BU_BEAUTIFIC_OEN_ENERGY<-detrend(ventes,marque='OENOBIOL_BU / BEAUTIFIC OEN ENERGY')
 OENOBIOL_BU_BEAUTIFIC_OEN_HAIR_A<-detrend(ventes,marque='OENOBIOL_BU / BEAUTIFIC OEN HAIR A')
 OENOBIOL_BU_BEAUTIFIC_OENOBIOL_A<-detrend(ventes,marque='OENOBIOL_BU / BEAUTIFIC OENOBIOL A')
 OENOBIOL_BU_BEAUTIFIC_OENOBIOL_S<-detrend(ventes,marque='OENOBIOL_BU / BEAUTIFIC OENOBIOL S')
 OENOBIOL_BU_BOUFFEES_DE_CHALEUR<-detrend(ventes,marque='OENOBIOL_BU / BOUFFEES DE CHALEUR')
 OENOBIOL_BU_CAPTEUR<-detrend(ventes,marque='OENOBIOL_BU / CAPTEUR')
 OENOBIOL_BU_CELLULITE<-detrend(ventes,marque='OENOBIOL_BU / CELLULITE')
 OENOBIOL_BU_CONFORT_DIGESTIF<-detrend(ventes,marque='OENOBIOL_BU / CONFORT DIGESTIF')
 OENOBIOL_BU_DESTRESSANT<-detrend(ventes,marque='OENOBIOL_BU / DESTRESSANT')
 OENOBIOL_BU_DETOX<-detrend(ventes,marque='OENOBIOL_BU / DETOX')
 OENOBIOL_BU_DIET_MINCEUR<-detrend(ventes,marque='OENOBIOL_BU / DIET MINCEUR')
 OENOBIOL_BU_DIV_SANTE_BIEN_ETRE<-detrend(ventes,marque='OENOBIOL_BU / DIV. SANTE&BIEN ETRE')
 OENOBIOL_BU_DIVERS_CAPILLAIRE<-detrend(ventes,marque='OENOBIOL_BU / DIVERS CAPILLAIRE')
 OENOBIOL_BU_DIVERS_FEMME_45<-detrend(ventes,marque='OENOBIOL_BU / DIVERS FEMME 45+')
 OENOBIOL_BU_DIVERS_MINCEUR<-detrend(ventes,marque='OENOBIOL_BU / DIVERS MINCEUR')
 OENOBIOL_BU_DIVERS_OENOBIOL<-detrend(ventes,marque='OENOBIOL_BU / DIVERS OENOBIOL')
 OENOBIOL_BU_DIVERS_PEAU<-detrend(ventes,marque='OENOBIOL_BU / DIVERS PEAU')
 OENOBIOL_BU_DIVERS_SOLAIRE<-detrend(ventes,marque='OENOBIOL_BU / DIVERS SOLAIRE')
 OENOBIOL_BU_ECLAT<-detrend(ventes,marque='OENOBIOL_BU / ECLAT')
 OENOBIOL_BU_FEMME45_ANTI_AGE<-detrend(ventes,marque='OENOBIOL_BU / FEMME45+ANTI AGE')
 OENOBIOL_BU_FORTIFIANT<-detrend(ventes,marque='OENOBIOL_BU / FORTIFIANT')
 OENOBIOL_BU_GLUCOMANANE<-detrend(ventes,marque='OENOBIOL_BU / GLUCOMANANE')
 OENOBIOL_BU_PEAU_d_ORANGE<-detrend(ventes,marque="OENOBIOL_BU / PEAU d'ORANGE")
 OENOBIOL_BU_PERFORMANCE<-detrend(ventes,marque='OENOBIOL_BU_PERFORMANCE')
 OENOBIOL_BU_PERTE_DE_POIDS<-detrend(ventes,marque='OENOBIOL_BU / PERTE DE POIDS')
 OENOBIOL_BU_PURIFIANT<-detrend(ventes,marque='OENOBIOL_BU / PURIFIANT')
 OENOBIOL_BU_REGARD<-detrend(ventes,marque='OENOBIOL_BU / REGARD')
 OENOBIOL_BU_REMODELANT<-detrend(ventes,marque='OENOBIOL_BU / REMODELANT')
 OENOBIOL_BU_RETENTION_D_EAU<-detrend(ventes,marque="OENOBIOL_BU / RETENTION D'EAU")
 OENOBIOL_BU_SOL_INT_NUTRI_PROT<-detrend(ventes,marque='OENOBIOL_BU / SOL. INT. NUTRI PROT')
 OENOBIOL_BU_SOL_INTENSIF_HYDRAT<-detrend(ventes,marque='OENOBIOL_BU / SOL.INTENSIF HYDRAT.')
 OENOBIOL_BU_SOL_INTENSIF_PROTEC<-detrend(ventes,marque='OENOBIOL_BU / SOL.INTENSIF PROTEC.')
 OENOBIOL_BU_SOL_INTENSIF_TOLER<-detrend(ventes,marque='OENOBIOL_BU / SOL.INTENSIF TOLER.')
 OENOBIOL_BU_SOLAIRE_INT_ANTI_AGE<-detrend(ventes,marque='OENOBIOL_BU / SOLAIRE INT.ANTI AGE')
 OENOBIOL_BU_SOLAIRE_INTENSIF<-detrend(ventes,marque='OENOBIOL_BU / SOLAIRE INTENSIF')
 OENOBIOL_BU_TOP_SLIM<-detrend(ventes,marque='OENOBIOL_BU / TOP SLIM')
 OENOBIOL_BU_TOP_SLIM_LIPOREDUCTE<-detrend(ventes,marque='OENOBIOL_BU / TOP SLIM LIPOREDUCTE')
 OENOBIOL_BU_ULTRA_HYDRATANT<-detrend(ventes,marque='OENOBIOL_BU / ULTRA HYDRATANT')
 OENOBIOL_BU_VENTRE_PLAT<-detrend(ventes,marque='OENOBIOL_BU / VENTRE PLAT')
 OENOBIOL_BU_VOLUMATEUR<-detrend(ventes,marque='OENOBIOL_BU / VOLUMATEUR')
 OTCDIV<-detrend(ventes,marque='OTCDIV')
 PHYSIOMER<-detrend(ventes,marque='PHYSIOMER')
 POLYKARAYA<-detrend(ventes,marque='POLYKARAYA')
 POLYSILANE<-detrend(ventes,marque='POLYSILANE')
 RESPILENE_BU<-detrend(ventes,marque='RESPILENE_BU')
 SOLUTRICINE<-detrend(ventes,marque='SOLUTRICINE')
 SORBITOL<-detrend(ventes,marque='SORBITOL')
 SPECIAFOLDINE<-detrend(ventes,marque='SPECIAFOLDINE')
 TOPLEXIL_BU<-detrend(ventes,marque='TOPLEXIL_BU')
 TROPHIRES<-detrend(ventes,marque='TROPHIRES')
 VADILEX<-detrend(ventes,marque='VADILEX')
 VITB12<-detrend(ventes,marque='VITB12')
 YOHIMBINE<-detrend(ventes,marque='YOHIMBINE')
 
 ## Fusion des tables
 fusion <- function(aspegique,marque='ASPEGIC/MIGPRIV') {
   date<-as.data.frame(unique(ventes$anneemois))
   date<-as.data.frame(date[order(date[,1]),])
   
   
   a<-as.data.frame(aspegique$x)
   names(a)<-'observed'
   b<-as.data.frame(aspegique$seasonal)
   names(b)<-'seasonal'
   c<-as.data.frame(aspegique$trend)
   names(c)<-'trend'
   d<-as.data.frame(aspegique$random)
   names(d)<-'random'
   date<-as.data.frame(date[1:nrow(a),])
   names(date)<-'anneemois'
   e<-cbind(date,list(a,b,c,d))
   e$segment_produit<-marque
   return(e)
 }
 
 
 aspegique	<-	fusion(aspegique	,marque='ASPEGIC/MIGPRIV')
 ATURGYL	<-	fusion(ATURGYL	,marque='ATURGYL')
 AVIBON	<-	fusion(AVIBON	,marque='AVIBON')
 BALSOFUMINE	<-	fusion(BALSOFUMINE	,marque='BALSOFUMINE')
 BRONCHOKOD_RHINATHIOL_BRONCHOKOD	<-	fusion(BRONCHOKOD_RHINATHIOL_BRONCHOKOD	,marque='BRONCHOKOD & RHINATHIOL / BRONCHOKOD')
 BRONCHOKOD_RHINATHIOL_RHINATHIOL	<-	fusion(BRONCHOKOD_RHINATHIOL_RHINATHIOL	,marque='BRONCHOKOD & RHINATHIOL / RHINATHIOL')
 CODOLIPRANE_BU	<-	fusion(CODOLIPRANE_BU	,marque='CODOLIPRANE_BU')
 DECONTRACT	<-	fusion(DECONTRACT	,marque='DECONTRACT')
 DERMACHROM	<-	fusion(DERMACHROM	,marque='DERMACHROM')
 DIAMOX	<-	fusion(DIAMOX	,marque='DIAMOX')
 #DOLI_ETAT_GRIPPAL	<-	fusion(DOLI_ETAT_GRIPPAL	,marque='DOLI_ETAT_GRIPPAL')
 DOLI_MAUX_DE_GORGE	<-	fusion(DOLI_MAUX_DE_GORGE	,marque='DOLI_MAUX_DE_GORGE')
 DOLIALLERGIE	<-	fusion(DOLIALLERGIE	,marque='DOLIALLERGIE')
 DOLIPRANE_GENERALIST	<-	fusion(DOLIPRANE_GENERALIST	,marque='DOLIPRANE GENERALIST')
 DOLIRHUME	<-	fusion(DOLIRHUME	,marque='DOLIRHUME')
 ENDOTELON_BU	<-	fusion(ENDOTELON_BU	,marque='ENDOTELON_BU')
 ERCEFURYL	<-	fusion(ERCEFURYL	,marque='ERCEFURYL')
 ETIOVEN	<-	fusion(ETIOVEN	,marque='ETIOVEN')
 HEMOCLAR	<-	fusion(HEMOCLAR	,marque='HEMOCLAR')
 HEPTAMYL	<-	fusion(HEPTAMYL	,marque='HEPTAMYL')
 HEXOMEDINE_BU	<-	fusion(HEXOMEDINE_BU	,marque='HEXOMEDINE_BU')
 IPRAALOX	<-	fusion(IPRAALOX	,marque='IPRAALOX')
 MAALOX	<-	fusion(MAALOX	,marque='MAALOX')
 MAGNE_B6_MAGNE_VIE	<-	fusion(MAGNE_B6_MAGNE_VIE	,marque='MAGNE B6 & MAGNE VIE')
 MAXILASE_BU	<-	fusion(MAXILASE_BU	,marque='MAXILASE_BU')
 MITOCORTYL	<-	fusion(MITOCORTYL	,marque='MITOCORTYL')
 MITOSYL	<-	fusion(MITOSYL	,marque='MITOSYL')
 NAUTAMINE	<-	fusion(NAUTAMINE	,marque='NAUTAMINE')
 NOVA_HEALTH_DIVERS_NOVA_SANTE	<-	fusion(NOVA_HEALTH_DIVERS_NOVA_SANTE	,marque='NOVA HEALTH / DIVERS NOVA SANTE')
 NOVA_HEALTH_NOVABIOSTIM	<-	fusion(NOVA_HEALTH_NOVABIOSTIM	,marque='NOVA HEALTH / NOVABIOSTIM')
 NOVA_HEALTH_NOVALGIC	<-	fusion(NOVA_HEALTH_NOVALGIC	,marque='NOVA HEALTH / NOVALGIC')
 NOVA_HEALTH_NOVANIGHT	<-	fusion(NOVA_HEALTH_NOVANIGHT	,marque='NOVA HEALTH / NOVANIGHT')
 NOVA_HEALTH_NOVASTEROL	<-	fusion(NOVA_HEALTH_NOVASTEROL	,marque='NOVA HEALTH / NOVASTEROL')
 NOVA_HEALTH_NOVASTIM	<-	fusion(NOVA_HEALTH_NOVASTIM	,marque='NOVA HEALTH / NOVASTIM')
 NOVA_HEALTH_NOVAZEN	<-	fusion(NOVA_HEALTH_NOVAZEN	,marque='NOVA HEALTH / NOVAZEN')
 #NOVALAC_BU	<-	fusion(NOVALAC_BU	,marque='NOVALAC_BU')
 OENOBIOL_BU_ACTIV_OPC	<-	fusion(OENOBIOL_BU_ACTIV_OPC	,marque='OENOBIOL_BU / ACTIV OPC')
 OENOBIOL_BU_ANTI_AGE	<-	fusion(OENOBIOL_BU_ANTI_AGE	,marque='OENOBIOL_BU / ANTIAGE')
 OENOBIOL_BU_ANTI_CHUTE	<-	fusion(OENOBIOL_BU_ANTI_CHUTE	,marque='OENOBIOL_BU / ANTICHUTE')
 OENOBIOL_BU_ANTI_RIDES	<-	fusion(OENOBIOL_BU_ANTI_RIDES	,marque='OENOBIOL_BU / ANTIRIDES')
 OENOBIOL_BU_AQUADRAINANT	<-	fusion(OENOBIOL_BU_AQUADRAINANT	,marque='OENOBIOL_BU / AQUADRAINANT')
 # OENOBIOL_BU_AUTOBRONZANT	<-	fusion(OENOBIOL_BU_AUTOBRONZANT	,marque='OENOBIOL_BU / AUTOBRONZANT')
 OENOBIOL_BU_BEAUTE_DES_CHEVEUX	<-	fusion(OENOBIOL_BU_BEAUTE_DES_CHEVEUX	,marque='OENOBIOL_BU / BEAUTE DES CHEVEUX')
 OENOBIOL_BU_BEAUTIFIC_OEN_ENERGY	<-	fusion(OENOBIOL_BU_BEAUTIFIC_OEN_ENERGY	,marque='OENOBIOL_BU / BEAUTIFIC OEN ENERGY')
 #OENOBIOL_BU_BEAUTIFIC_OEN_HAIR_A	<-	fusion(OENOBIOL_BU_BEAUTIFIC_OEN_HAIR_A	,marque='OENOBIOL_BU / BEAUTIFIC OEN HAIR A')
 #OENOBIOL_BU_BEAUTIFIC_OENOBIOL_A	<-	fusion(OENOBIOL_BU_BEAUTIFIC_OENOBIOL_A	,marque='OENOBIOL_BU / BEAUTIFIC OENOBIOL A')
 #OENOBIOL_BU_BEAUTIFIC_OENOBIOL_S	<-	fusion(OENOBIOL_BU_BEAUTIFIC_OENOBIOL_S	,marque='OENOBIOL_BU / BEAUTIFIC OENOBIOL S')
 OENOBIOL_BU_BOUFFEES_DE_CHALEUR	<-	fusion(OENOBIOL_BU_BOUFFEES_DE_CHALEUR	,marque='OENOBIOL_BU / BOUFFEES DE CHALEUR')
 #OENOBIOL_BU_CAPTEUR	<-	fusion(OENOBIOL_BU_CAPTEUR	,marque='OENOBIOL_BU / CAPTEUR')
 OENOBIOL_BU_CELLULITE	<-	fusion(OENOBIOL_BU_CELLULITE	,marque='OENOBIOL_BU / CELLULITE')
 OENOBIOL_BU_CONFORT_DIGESTIF	<-	fusion(OENOBIOL_BU_CONFORT_DIGESTIF	,marque='OENOBIOL_BU / CONFORT DIGESTIF')
 OENOBIOL_BU_DESTRESSANT	<-	fusion(OENOBIOL_BU_DESTRESSANT	,marque='OENOBIOL_BU / DESTRESSANT')
 OENOBIOL_BU_DETOX	<-	fusion(OENOBIOL_BU_DETOX	,marque='OENOBIOL_BU / DETOX')
 OENOBIOL_BU_DIET_MINCEUR	<-	fusion(OENOBIOL_BU_DIET_MINCEUR	,marque='OENOBIOL_BU / DIET MINCEUR')
 OENOBIOL_BU_DIV_SANTE_BIEN_ETRE	<-	fusion(OENOBIOL_BU_DIV_SANTE_BIEN_ETRE	,marque='OENOBIOL_BU / DIV. SANTE&BIEN ETRE')
 #OENOBIOL_BU_DIVERS_CAPILLAIRE	<-	fusion(OENOBIOL_BU_DIVERS_CAPILLAIRE	,marque='OENOBIOL_BU / DIVERS CAPILLAIRE')
 #OENOBIOL_BU_DIVERS_FEMME_45	<-	fusion(OENOBIOL_BU_DIVERS_FEMME_45	,marque='OENOBIOL_BU / DIVERS FEMME 45+')
 OENOBIOL_BU_DIVERS_MINCEUR	<-	fusion(OENOBIOL_BU_DIVERS_MINCEUR	,marque='OENOBIOL_BU / DIVERS MINCEUR')
 OENOBIOL_BU_DIVERS_OENOBIOL	<-	fusion(OENOBIOL_BU_DIVERS_OENOBIOL	,marque='OENOBIOL_BU / DIVERS OENOBIOL')
 OENOBIOL_BU_DIVERS_PEAU	<-	fusion(OENOBIOL_BU_DIVERS_PEAU	,marque='OENOBIOL_BU / DIVERS PEAU')
 #OENOBIOL_BU_DIVERS_SOLAIRE	<-	fusion(OENOBIOL_BU_DIVERS_SOLAIRE	,marque='OENOBIOL_BU / DIVERS SOLAIRE')
 OENOBIOL_BU_ECLAT	<-	fusion(OENOBIOL_BU_ECLAT	,marque='OENOBIOL_BU / ECLAT')
 OENOBIOL_BU_FEMME45_ANTI_AGE	<-	fusion(OENOBIOL_BU_FEMME45_ANTI_AGE	,marque='OENOBIOL_BU / FEMME45+ANTI AGE')
 OENOBIOL_BU_FORTIFIANT	<-	fusion(OENOBIOL_BU_FORTIFIANT	,marque='OENOBIOL_BU / FORTIFIANT')
 OENOBIOL_BU_GLUCOMANANE	<-	fusion(OENOBIOL_BU_GLUCOMANANE	,marque='OENOBIOL_BU / GLUCOMANANE')
 #OENOBIOL_BU_PEAU_d_ORANGE	<-	fusion(OENOBIOL_BU_PEAU_d_ORANGE	,marque="OENOBIOL_BU / PEAU d'ORANGE")
 #OENOBIOL_BU_PERFORMANCE	<-	fusion(OENOBIOL_BU_PERFORMANCE	,marque='OENOBIOL_BU_PERFORMANCE')
 OENOBIOL_BU_PERTE_DE_POIDS	<-	fusion(OENOBIOL_BU_PERTE_DE_POIDS	,marque='OENOBIOL_BU / PERTE DE POIDS')
 OENOBIOL_BU_PURIFIANT	<-	fusion(OENOBIOL_BU_PURIFIANT	,marque='OENOBIOL_BU / PURIFIANT')
 OENOBIOL_BU_REGARD	<-	fusion(OENOBIOL_BU_REGARD	,marque='OENOBIOL_BU / REGARD')
 OENOBIOL_BU_REMODELANT	<-	fusion(OENOBIOL_BU_REMODELANT	,marque='OENOBIOL_BU / REMODELANT')
 OENOBIOL_BU_RETENTION_D_EAU	<-	fusion(OENOBIOL_BU_RETENTION_D_EAU	,marque="OENOBIOL_BU / RETENTION D'EAU")
 OENOBIOL_BU_SOL_INT_NUTRI_PROT	<-	fusion(OENOBIOL_BU_SOL_INT_NUTRI_PROT	,marque='OENOBIOL_BU / SOL. INT. NUTRI PROT')
 OENOBIOL_BU_SOL_INTENSIF_HYDRAT	<-	fusion(OENOBIOL_BU_SOL_INTENSIF_HYDRAT	,marque='OENOBIOL_BU / SOL.INTENSIF HYDRAT.')
 OENOBIOL_BU_SOL_INTENSIF_PROTEC	<-	fusion(OENOBIOL_BU_SOL_INTENSIF_PROTEC	,marque='OENOBIOL_BU / SOL.INTENSIF PROTEC.')
 OENOBIOL_BU_SOL_INTENSIF_TOLER	<-	fusion(OENOBIOL_BU_SOL_INTENSIF_TOLER	,marque='OENOBIOL_BU / SOL.INTENSIF TOLER.')
 OENOBIOL_BU_SOLAIRE_INT_ANTI_AGE	<-	fusion(OENOBIOL_BU_SOLAIRE_INT_ANTI_AGE	,marque='OENOBIOL_BU / SOLAIRE INT.ANTI AGE')
 OENOBIOL_BU_SOLAIRE_INTENSIF	<-	fusion(OENOBIOL_BU_SOLAIRE_INTENSIF	,marque='OENOBIOL_BU / SOLAIRE INTENSIF')
 OENOBIOL_BU_TOP_SLIM	<-	fusion(OENOBIOL_BU_TOP_SLIM	,marque='OENOBIOL_BU / TOP SLIM')
 #OENOBIOL_BU_TOP_SLIM_LIPOREDUCTE	<-	fusion(OENOBIOL_BU_TOP_SLIM_LIPOREDUCTE	,marque='OENOBIOL_BU / TOP SLIM LIPOREDUCTE')
 OENOBIOL_BU_ULTRA_HYDRATANT	<-	fusion(OENOBIOL_BU_ULTRA_HYDRATANT	,marque='OENOBIOL_BU / ULTRA HYDRATANT')
 OENOBIOL_BU_VENTRE_PLAT	<-	fusion(OENOBIOL_BU_VENTRE_PLAT	,marque='OENOBIOL_BU / VENTRE PLAT')
 OENOBIOL_BU_VOLUMATEUR	<-	fusion(OENOBIOL_BU_VOLUMATEUR	,marque='OENOBIOL_BU / VOLUMATEUR')
 OTCDIV	<-	fusion(OTCDIV	,marque='OTCDIV')
 PHYSIOMER	<-	fusion(PHYSIOMER	,marque='PHYSIOMER')
 POLYKARAYA	<-	fusion(POLYKARAYA	,marque='POLYKARAYA')
 POLYSILANE	<-	fusion(POLYSILANE	,marque='POLYSILANE')
 RESPILENE_BU	<-	fusion(RESPILENE_BU	,marque='RESPILENE_BU')
 SOLUTRICINE	<-	fusion(SOLUTRICINE	,marque='SOLUTRICINE')
 SORBITOL	<-	fusion(SORBITOL	,marque='SORBITOL')
 SPECIAFOLDINE	<-	fusion(SPECIAFOLDINE	,marque='SPECIAFOLDINE')
 TOPLEXIL_BU	<-	fusion(TOPLEXIL_BU	,marque='TOPLEXIL_BU')
 TROPHIRES	<-	fusion(TROPHIRES	,marque='TROPHIRES')
 VADILEX	<-	fusion(VADILEX	,marque='VADILEX')
 VITB12	<-	fusion(VITB12	,marque='VITB12')
 #YOHIMBINE	<-	fusion(YOHIMBINE	,marque='YOHIMBINE')
 
 

 l<-list(aspegique,ATURGYL,AVIBON,BALSOFUMINE,BRONCHOKOD_RHINATHIOL_BRONCHOKOD,BRONCHOKOD_RHINATHIOL_RHINATHIOL,
         CODOLIPRANE_BU,DECONTRACT,DERMACHROM,DIAMOX,DOLI_MAUX_DE_GORGE,DOLIALLERGIE,DOLIPRANE_GENERALIST,
         DOLIRHUME,ENDOTELON_BU,ERCEFURYL,ETIOVEN,HEMOCLAR,HEPTAMYL,HEXOMEDINE_BU,IPRAALOX,MAALOX,MAGNE_B6_MAGNE_VIE,
         MAXILASE_BU,MITOCORTYL,MITOSYL,NAUTAMINE,NOVA_HEALTH_DIVERS_NOVA_SANTE,NOVA_HEALTH_NOVABIOSTIM,
         NOVA_HEALTH_NOVALGIC,NOVA_HEALTH_NOVANIGHT,NOVA_HEALTH_NOVASTEROL,NOVA_HEALTH_NOVASTIM,NOVA_HEALTH_NOVAZEN,
         OENOBIOL_BU_ACTIV_OPC,OENOBIOL_BU_ANTI_AGE,OENOBIOL_BU_ANTI_CHUTE,OENOBIOL_BU_ANTI_RIDES,OENOBIOL_BU_AQUADRAINANT,
         OENOBIOL_BU_BEAUTE_DES_CHEVEUX,OENOBIOL_BU_BEAUTIFIC_OEN_ENERGY,OENOBIOL_BU_BOUFFEES_DE_CHALEUR,OENOBIOL_BU_CELLULITE,
         OENOBIOL_BU_CONFORT_DIGESTIF,OENOBIOL_BU_DESTRESSANT,OENOBIOL_BU_DETOX,OENOBIOL_BU_DIET_MINCEUR,OENOBIOL_BU_DIV_SANTE_BIEN_ETRE,
         OENOBIOL_BU_DIVERS_MINCEUR,OENOBIOL_BU_DIVERS_OENOBIOL,OENOBIOL_BU_DIVERS_PEAU,OENOBIOL_BU_ECLAT,OENOBIOL_BU_FEMME45_ANTI_AGE,
         OENOBIOL_BU_FORTIFIANT,OENOBIOL_BU_GLUCOMANANE,OENOBIOL_BU_PERTE_DE_POIDS,OENOBIOL_BU_PURIFIANT,OENOBIOL_BU_REGARD,
         OENOBIOL_BU_REMODELANT,OENOBIOL_BU_RETENTION_D_EAU,OENOBIOL_BU_SOL_INT_NUTRI_PROT,OENOBIOL_BU_SOL_INTENSIF_HYDRAT,
         OENOBIOL_BU_SOL_INTENSIF_PROTEC,OENOBIOL_BU_SOL_INTENSIF_TOLER,OENOBIOL_BU_SOLAIRE_INT_ANTI_AGE,OENOBIOL_BU_SOLAIRE_INTENSIF,
         OENOBIOL_BU_TOP_SLIM,OENOBIOL_BU_ULTRA_HYDRATANT,OENOBIOL_BU_VENTRE_PLAT,OENOBIOL_BU_VOLUMATEUR,OTCDIV,PHYSIOMER,POLYKARAYA,
         POLYSILANE,RESPILENE_BU,SOLUTRICINE,SORBITOL,SPECIAFOLDINE,TOPLEXIL_BU,TROPHIRES,VADILEX,VITB12
 )
 
 season<-rbindlist(l, fill=FALSE, idcol=NULL)
 
 write.csv(season,"season.csv")
 
 
 
 

 
 
 
 
 
 #toplex_SMA3 <- SMA(toplex,n=3)
 #plot.ts(toplex_SMA3)
 
 
 toplex_components <- decompose(toplex)
 
 plot(toplex_components)
 par(mfrow = c(1, 1))
 toplex_forecasts <- HoltWinters(toplex, beta=FALSE, gamma=FALSE)
 
 toplex_forecasts$fitted
 plot(toplex_forecasts)
 
 
 library("forecast")
 
 toplex_forecasts2 <- forecast.HoltWinters(toplex_forecasts, h=12)
 
 plot.forecast(toplex_forecasts2)
 
 acf(toplex_forecasts2$residuals, lag.max=20)
 plot.ts(toplex_forecasts2$residuals)
 
 
 toplex_forecasts <- HoltWinters(toplex, gamma=FALSE)
 
 toplex_forecasts$fitted
 plot(toplex_forecasts)
 
 fit = stl(toplex, s.window="periodic")
 plot(fit)

 
 